name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello and welcome! Before contributing to this project, please make sure you review and agree with the CLA[https://github.com/Proxati/llm_proxy/blob/main/CLA.md]."
        pr-message: "Thank you for your contribution to our project. Before proceeding, please review and agree to the Contributor License Agreement (CLA) available at https://github.com/Proxati/llm_proxy/blob/main/CLA.md. By submitting this and any future pull requests, you are agreeing to the terms outlined in the CLA."
